version: '2'
services:
    app:
        image: php:7-apache
        ports:
        - "${public_port}:80"
        restart: always
        tty: true
        stdin_open: true
        volumes_from:
        - app-data:ro
        labels:
            io.rancher.sidekicks: app-data
    app-data:
        image: emarref/hello-world
        labels:
            io.rancher.container.start_once: 'true'
        volumes:
        - /var/www/html
        net: none
        command: /bin/true
